name: DAST Scan with Nuclei

on:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start application
        run: docker compose up -d --build

      - name: Wait for API Gateway
        run: |
          until curl -s http://localhost/api/users/health; do
            echo "Waiting..."
            sleep 3
          done

      - name: Run Nuclei scan
        run: |
          GATEWAY_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q --filter "name=gateway"))
          docker run --rm -v $(pwd):/tmp projectdiscovery/nuclei:latest -u http://$GATEWAY_IP -o /tmp/nuclei_report.txt

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-dast-report
          path: nuclei_report.txt
